parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # App
    App\:
        resource: '../src/App'

    App\Http\Handler\:
        resource: '../src/App/Http/Handler/'
        tags: [ 'controller.service_arguments' ]

    # Tests
    Test\Functional\:
        resource: '../tests/Functional/**/*Fixture.php'
        tags: [ 'doctrine.fixture.orm' ]

    # HTTP
    App\Http\Response\ResponseFactory:
        class: App\Infrastructure\Http\Response\SymfonyResponseFactory

    # Services
    App\Service\UuidGenerator:
        class: App\Infrastructure\Service\RamseyUuidGenerator

    App\Service\ValidatorInterface:
        class: App\Infrastructure\Service\SymfonyValidator

    App\Service\FileUploader:
        class: App\Infrastructure\Service\Uploader\FlysystemFileUploader
        arguments: ['@default.storage']

    # Domain
    Domain\:
        resource: '../src/Domain'

    # Domain Services
    Domain\FlusherInterface:
        class: Domain\Infrastructure\DoctrineFlusher

    Domain\PersisterInterface:
        class: Domain\Infrastructure\DoctrinePersister

    Domain\EntityRemoverInterface:
        class: Domain\Infrastructure\DoctrineEntityRemover

    # User
    User\:
        resource: '../src/User'

    # User Services
    User\ReadModel\UserFetcher:
        class: User\Infrastructure\ReadModel\DoctrineUserFetcher

    User\Factory\UserFactoryInterface:
        class: User\Infrastructure\Factory\UserFactory

    User\Service\HasherInterface:
        class: User\Infrastructure\Service\Hasher

    User\Service\PasswordValidatorInterface:
        class: User\Infrastructure\Service\PasswordValidator

    User\Model\UserRepositoryInterface:
        class: User\Infrastructure\Model\DoctrineUserRepository

    # Messenger
    Messenger\:
        resource: '../src/Messenger'

    # Author
    Messenger\Model\Author\AuthorRepositoryInterface:
        class: Messenger\Infrastructure\Model\Author\DoctrineAuthorRepository

    # Message
    Messenger\Model\Message\MessageRepositoryInterface:
        class: Messenger\Infrastructure\Model\Message\DoctrineMessageRepository

    # Dialog
    Messenger\Model\Dialog\DialogRepositoryInterface:
        class: Messenger\Infrastructure\Model\Dialog\DoctrineDialogRepository

    Messenger\ReadModel\DialogFetcherInterface:
        class: Messenger\Infrastructure\ReadModel\DoctrineDialogFetcher
