parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # TODO: Separate config

    # App
    App\:
        resource: '../src/App'

    App\Http\Handler\:
        resource: '../src/App/Http/Handler/'
        tags: [ 'controller.service_arguments' ]

    # HTTP
    App\Http\Response\ResponseFactory:
        class: App\Infrastructure\Http\Response\SymfonyResponseFactory

    # Domain
    Domain\:
        resource: '../src/Domain'

    # Domain Services
    Domain\FlusherInterface:
        class: Domain\Infrastructure\DoctrineFlusher

    Domain\PersisterInterface:
        class: Domain\Infrastructure\DoctrinePersister

    # User
    User\:
        resource: '../src/User'

    # User Services
    User\Factory\UserFactoryInterface:
        class: User\Infrastructure\Factory\UserFactory

    User\Service\HasherInterface:
        class: User\Infrastructure\Service\Hasher

    User\Model\UserRepositoryInterface:
        class: User\Infrastructure\Model\DoctrineUserRepository
